### ISSUE TITLE
Android support?

### ISSUE THREAD

**Issue by patoroco** [almost/react-native-html-webview#13]
Hi,

do you have any plan about Android support with this library?

react-native currently doesn't have official WebView, so it should be interesting to have the same component in both platforms.

Thanks.

**Comment by almost** [comment]
React Native does actually have a webview built in:

http://facebook.github.io/react-native/docs/webview.html

**Comment by patoroco** [comment]
It's strange, because on the one hand they talk about webviews in android as a future plan (http://facebook.github.io/react-native/docs/known-issues.html#views), but on the other hand, they have some properties with android suffixes (i.e. http://facebook.github.io/react-native/docs/webview.html#javascriptenabledandroid).

Anyway, I'm getting a `No ViewManager defined for class RCTWebView` error, which I was googling, and I found this issue: https://github.com/facebook/react-native/issues/2701 which refer directly to the first link that I wrote (http://facebook.github.io/react-native/docs/known-issues.html#views).
