### ISSUE TITLE
Couldn't get it working with my project

### ISSUE THREAD

**Issue by strazi** [almost/react-native-html-webview#2]
Here are some things I had to do:
1. Under Search Paths, I added: `$(SRCROOT)/../react-native/React` and `recursive` to get it to build.
2. I added `RCT_EXPORT_MODULE();` to AIBHTMLWebViewManager.m because the error message in the simulator said it was missing.

After that it looks like it's working great, I'm just wondering if your config or mine is somehow different.

**Comment by almost** [comment]
Thanks for this! Looks like RCT_EXPORT_MODULE is new in React Native 0.3.8 released 3 days ago. All part of the fun of being on the bleeding edge ;) I've published a fixed version to npm just now.

I think the Search Paths change may be to do with how you have React Native installed. With React Native installed via NPM (so living in `node_modules`) it should just work.
