### ISSUE TITLE
Cannot run on IOS

### ISSUE THREAD

**Issue by mvpdream** [almost/react-native-html-webview#21]
![8b8b5052-14ff-477a-be3d-9f727b40cfb2](https://cloud.githubusercontent.com/assets/16203724/17882927/01c86cea-6942-11e6-809a-6988f590de75.png)

**Comment by almost** [comment]
It probably won't work with recent RN versions. See the note in the readme, you can do most of what this does with the built in WebView now

**Comment by mvpdream** [comment]
This is the error message 

/Users/xmc/Desktop/RNprojects/RN_iOS_App/node_modules/react-native/React/Base/RCTConvert.h:13:9: 'CSSLayout/CSSLayout.h' file not found with <angled> include; use "quotes" instead

may be required to introduce what files, I do not understand IOS development, I hope you help solve the next.

**Comment by almost** [comment]
As I said this won't work with recent RN versions and there's no much point in using anymore anyway.

**Comment by mvpdream** [comment]
That problem has been solved, and now there is a new problem. I hope you can help me to solve the next.
![image](https://cloud.githubusercontent.com/assets/16203724/17914954/05f8ac2a-69d9-11e6-8dac-8951922f109e.png)
