### ISSUE TITLE
My app crashed after I require the component .How to solve the problem?(react 0.10.0-rc)

### ISSUE THREAD

**Issue by everfire130** [almost/react-native-html-webview#8]
Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'customDirectEventTypes must return an array, but AIBHTMLWebViewManager returned __NSDictionaryI'

**Comment by ninamanalo** [comment]
same error here

```
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'customDirectEventTypes must return an array, but AIBHTMLWebViewManager returned __NSDictionaryI'
```

**Comment by almost** [comment]
This is a change in RN 0.10.0-rc: https://github.com/facebook/react-native/commit/48af214216ce2b180035b44b4a9a7cbb010073ca

I've pushed a fix to master but don't have time to test properly now. Could someone please try it and let me know if it's ok?

**Comment by ninamanalo** [comment]
Thanks for the update. It already works when I launched the app, but still haven't tested if there are effects on the library functionalities.

**Comment by almost** [comment]
Thanks @ninamanalo, I've also now had a chance to test it so I've pushed a
new release to NPM
